version: '3.8'
services:
  jupyter:
    image: aeon/jupyter
    build: '.'
    working_dir: /content
    environment:
      - NVIDIA_DISABLE_REQUIRE=1 # https://github.com/NVIDIA/nvidia-docker/issues/1409#issuecomment-778089784
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    volumes: [ './entrypoint.sh:/entrypoint.sh', './:/content' ]
    ports: [ '127.0.0.1:8888:8888/tcp' ]
